---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - releasers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - devops.kubesphere.io
  resources:
  - releasers/finalizers
  verbs:
  - update
- apiGroups:
  - devops.kubesphere.io
  resources:
  - releasers/status
  verbs:
  - get
  - patch
  - update
