---
apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ks-releaser
  name: ks-releaser
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ks-releaser
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ks-releaser
    spec:
      containers:
        - image: surenpi/releaser
          name: server
          env:
            - name: WEBHOOK
              value: "false"
