name: Release Drafter

on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  UpdateReleaseDraft:
    runs-on: ubuntu-20.04
    steps:
      - uses: release-drafter/release-drafter@v6
        env:
          GITHUB_TOKEN: ${{ secrets.GH_PUBLISH_SECRETS }}
